services:
  # A backend which provides basic authentication and CRUD access to the Postgres DB from the client
  demo-backend:
    depends_on:
      pg-db:
        condition: service_healthy
    build:
      context: https://github.com/powersync-ja/powersync-django-backend-todolist-demo.git
    environment:
      # From the Postgres service name in linked Docker Compose file
      DATABASE_HOST: pg-db
      # Shared environment variables for Postgres connection
      DATABASE_PORT: ${PG_DATABASE_PORT}
      DATABASE_NAME: ${PG_DATABASE_NAME}
      DATABASE_USER: ${PG_DATABASE_USER}
      DATABASE_PASSWORD: ${PG_DATABASE_PASSWORD}

      # From the PowerSync service name
      # This is just used to populate the JWT audience
      POWERSYNC_URL: powersync-dev

      # Keys here for demonstration
      POWERSYNC_PUBLIC_KEY: ${DEMO_JWKS_PUBLIC_KEY}
      POWERSYNC_PRIVATE_KEY: ${DEMO_JWKS_PRIVATE_KEY}

      DJANGO_PORT: ${DEMO_BACKEND_PORT}
    ports:
      - ${DEMO_BACKEND_PORT}:${DEMO_BACKEND_PORT}
