receivers:
  otlp:
    protocols:
      http:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:7654"

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
      processors: [batch]
