global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["telemetry-collector:7654"]
