{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "powersync_concurrent_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows Replicated Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "powersync_rows_replicated_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Replicated Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "powersync_transactions_replicated_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parameter Storage Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "powersync_parameter_storage_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Storage Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "powersync_replication_storage_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation Storage Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "powersync_operation_storage_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Synced Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "powersync_operations_synced_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunks Replicated Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "powersync_chunks_replicated_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Replicated Total (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "powersync_data_replicated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}