# Include syntax requires Docker compose > 2.20.3
# https://docs.docker.com/compose/release-notes/#2203
include:
  # Demo NodeJS backend server and front-end web client
  - path: ../nodejs/ps-nodejs-demo.yaml

services:
  # Extend PowerSync with Mongo and Postgres healthchecks
  powersync:
    extends:
      file: ../../services/powersync.yaml
      service: powersync
    depends_on:
      pg-db:
        condition: service_healthy
      pg-storage:
        condition: service_healthy
    volumes:
      - ./config:/config
    environment:
      PS_STORAGE_SOURCE_URI: ${PS_STORAGE_SOURCE_URI}
  pg-db:
    extends:
      file: ../../services/postgres.yaml
      service: pg-db
    volumes:
      - ../nodejs/init-scripts:/docker-entrypoint-initdb.d

  pg-storage:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PG_STORAGE_DATABASE_USER}
      - POSTGRES_DB=${PG_STORAGE_DATABASE_NAME}
      - POSTGRES_PASSWORD=${PG_STORAGE_DATABASE_PASSWORD}
      - PGPORT=${PG_STORAGE_DATABASE_PORT}
    volumes:
      - pg_storage_data:/var/lib/postgresql/data
    ports:
      - "${PG_STORAGE_DATABASE_PORT}:${PG_STORAGE_DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_STORAGE_DATABASE_USER} -d ${PG_STORAGE_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_storage_data:
  pg_data:
