config:
  edition: 3

streams:
  user_lists:
    auto_subscribe: true
    query: SELECT uuid AS id, * FROM lists WHERE owner_id = substring(auth.user_id(), 1, 32)

  user_todos:
    auto_subscribe: true
    query: SELECT uuid AS id, * FROM todos WHERE list_uuid IN (SELECT uuid FROM lists WHERE owner_id = substring(auth.user_id(), 1, 32))
