name: mssql-selfhosted-db
services:
  mssql-selfhosted:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest  # 2025 Can also be used, but not on Mac 26 Tahoe due to this issue: https://github.com/microsoft/mssql-docker/issues/942
    container_name: mssql-selfhosted
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"   # required for CDC capture/cleanup jobs
    volumes:
      - mssql-selfhosted-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1;\" || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  mssql-selfhosted-setup:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-selfhosted-setup
    depends_on:
      mssql-selfhosted:
        condition: service_healthy
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      APP_DB: "${APP_DB}"
      APP_LOGIN: "${APP_LOGIN}"
      APP_PASSWORD: "${APP_PASSWORD}"
    volumes:
      - ./init.sql:/scripts/init.sql:ro
    entrypoint: ["/bin/bash", "-lc", "/opt/mssql-tools18/bin/sqlcmd -C -S mssql-selfhosted,1433 -U sa -P \"$SA_PASSWORD\" -i /scripts/init.sql && echo '✅ MSSQL init done'"]

volumes:
  mssql-selfhosted-data:
